name: example
description: An example of using vsc_quill_delta_to_html in Flutter and on server-side (or CLI) Dart.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_quill: ^4.2.3
  url_launcher: ^6.1.8
  vsc_quill_delta_to_html:
    path: ../

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
